name: Test workflow

on: workflow_dispatch

jobs:
  print-repo-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: RepoName
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
