name: Test workflow

on: workflow_dispatch

jobs:
  print-repo-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: RepoName
        run:  |
          echo "Repository Name: ${{ github.repository }}"
          echo "Branch Name: ${{ github.ref_name }}"
  build-console-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Console Project
        run: dotnet new console --name todo
      - name: Setup .net
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 9
        
