name: Test workflow

on: workflow_dispatch

jobs:
  print-repo-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: RepoName
        run:  |
          echo "Repository Name: ${{ github.repository }}"
          echo "Branch Name: ${{ github.ref_name }}"
