name: Test workflow

on: 
  push:
    paths:
      - '**/*.cs*'

jobs:
  print-repo-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: RepoName
        run:  |
          echo "Repository Name: ${{ github.repository }}"
          echo "Branch Name: ${{ github.ref_name }}"
  #build-console-project:
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v4
      #- name: Setup .net
     #   uses: actions/setup-dotnet@v4.1.0
      #  with:
      #    dotnet-version: 9
     # - name: Create Console Project
     #   run: dotnet new console --name todo
     # - name: Commit and Push
     #   run: |
      #    git config --global user.name "github-actions[bot]"
      #    git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #    git add .
      #    git commit -m "Add new console project"
      #    git push
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
