name: PR Workflow

on: 
  pull_request:
    types: [opened]

jobs: 
  log-PR:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Log Pull Request
        run: echo "Pull request done at $(date) by - ${{ github.actor }}" >> README.md
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "PR-creation logged"
          git push
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
